### ISSUE TITLE
groovy build failing to link timestamp_tools

### ISSUE THREAD

**Issue by tfoote** [ros-drivers/wge100_driver#1]
http://jenkins.willowgarage.com:8080/view/GbinO64/job/ros-groovy-wge100-driver_binarydeb_oneiric_amd64/62/console

```
  /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/wge100lib.c: In function 'wge100ReliableFlashWrite':
  /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/wge100lib.c:1018:7: warning: variable 'first_read' set but not used [-Wunused-but-set-variable]
  [ 42%] Building C object src/wge100lib/CMakeFiles/wge100camera.dir/list.c.o
  /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/list.c: In function 'wge100CamListDelAll':
  /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/list.c:192:6: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  Linking CXX shared library ../../../lib/libwge100camera.so
  /usr/bin/ld: cannot find -ltimestamp_tools
  collect2: ld returned 1 exit status
  make[5]: *** [../lib/libwge100camera.so] Error 1
  make[5]: Leaving directory `/tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/build'
  make[4]: *** [src/wge100lib/CMakeFiles/wge100camera.dir/all] Error 2
  make[4]: Leaving directory `/tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/build'
  make[3]: *** [all] Error 2
  make[3]: Leaving directory `/tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/build'
  make[2]: *** [all] Error 2
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package wge100_camera written to:
[ rosmake ]    /tmp/.ros/rosmake/rosmake_output-20121209-001228/wge100_camera/build_output.log
[rosmake-1] Finished <<< wge100_camera [FAIL] [ 35.63 seconds ]       
```

**Comment by wjwwood** [comment]
This is fixed. #close

On Sun, Dec 9, 2012 at 1:36 AM, Tully Foote notifications@github.comwrote:

> http://jenkins.willowgarage.com:8080/view/GbinO64/job/ros-groovy-wge100-driver_binarydeb_oneiric_amd64/62/console
> 
>   /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/wge100lib.c: In function 'wge100ReliableFlashWrite':
>   /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/wge100lib.c:1018:7: warning: variable 'first_read' set but not used [-Wunused-but-set-variable]
>   [ 42%] Building C object src/wge100lib/CMakeFiles/wge100camera.dir/list.c.o
>   /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/list.c: In function 'wge100CamListDelAll':
>   /tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/src/wge100lib/list.c:192:6: warning: variable 'count' set but not used [-Wunused-but-set-variable]
>   Linking CXX shared library ../../../lib/libwge100camera.so
>   /usr/bin/ld: cannot find -ltimestamp_tools
>   collect2: ld returned 1 exit status
>   make[5]: **\* [../lib/libwge100camera.so] Error 1
>   make[5]: Leaving directory `/tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/build'
>   make[4]: *** [src/wge100lib/CMakeFiles/wge100camera.dir/all] Error 2
>   make[4]: Leaving directory`/tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/build'
>   make[3]: **\* [all] Error 2
>   make[3]: Leaving directory `/tmp/buildd/ros-groovy-wge100-driver-1.7.4/debian/ros-groovy-wge100-driver/opt/ros/groovy/stacks/wge100_driver/wge100_camera/build'
>   make[2]: **\* [all] Error 2
> -------------------------------------------------------------------------------}
> [ rosmake ] Output from build of package wge100_camera written to:
> [ rosmake ]    /tmp/.ros/rosmake/rosmake_output-20121209-001228/wge100_camera/build_output.log
> [rosmake-1] Finished <<< wge100_camera [FAIL] [ 35.63 seconds ]
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-drivers/wge100_driver/issues/1.

## 

William Woodall
Willow Garage - Software Engineer
wwoodall@willowgarage.com
